set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/s_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axis_data_fifo_0/m_axis_tdata[30]}]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_0/m_axis_tvalid]
set_property MARK_DEBUG false [get_nets design_1_i/axis_data_fifo_0/s_axis_tready]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_0/s_axis_tlast]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_0/s_axis_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_0/m_axis_tlast]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0/s_axi_lite_wdata[29]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_0/s_axi_lite_rvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_0/s_axi_lite_wvalid]


set_property PACKAGE_PIN M17 [get_ports {DB[15]}]
set_property PACKAGE_PIN L17 [get_ports {DB[14]}]
set_property PACKAGE_PIN P21 [get_ports {DB[13]}]
set_property PACKAGE_PIN N18 [get_ports {DB[12]}]
set_property PACKAGE_PIN N22 [get_ports {DB[11]}]
set_property PACKAGE_PIN R20 [get_ports {DB[10]}]
set_property PACKAGE_PIN J18 [get_ports {DB[9]}]
set_property PACKAGE_PIN L22 [get_ports {DB[8]}]
set_property PACKAGE_PIN M20 [get_ports {DB[7]}]
set_property PACKAGE_PIN J22 [get_ports {DB[6]}]
set_property PACKAGE_PIN T17 [get_ports {DB[5]}]
set_property PACKAGE_PIN M22 [get_ports {DB[4]}]
set_property PACKAGE_PIN P22 [get_ports {DB[3]}]
set_property PACKAGE_PIN P18 [get_ports {DB[2]}]
set_property PACKAGE_PIN N20 [get_ports {DB[1]}]
set_property PACKAGE_PIN N19 [get_ports {DB[0]}]
set_property PACKAGE_PIN T16 [get_ports BUSY]
set_property PACKAGE_PIN K18 [get_ports CNVST]
set_property PACKAGE_PIN M21 [get_ports CS]
set_property PACKAGE_PIN J21 [get_ports FRSTDATA]
set_property PACKAGE_PIN T22 [get_ports led_0]
set_property PACKAGE_PIN M19 [get_ports SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports led_0]
set_property IOSTANDARD LVCMOS25 [get_ports FRSTDATA]
set_property IOSTANDARD LVCMOS25 [get_ports CS]
set_property IOSTANDARD LVCMOS25 [get_ports CNVST]
set_property IOSTANDARD LVCMOS25 [get_ports BUSY]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {DB[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0_M00_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0_M00_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_0_M_AXIS_MM2S_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/CNVST]
set_property MARK_DEBUG true [get_nets design_1_i/CS]
set_property MARK_DEBUG true [get_nets design_1_i/SCLK]
set_property MARK_DEBUG true [get_nets design_1_i/FRSTDATA]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/DB[15]}]
set_property MARK_DEBUG true [get_nets design_1_i/BUSY]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[27]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_0_M_AXIS_MM2S_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_0_M_AXIS_MM2S_TVALID]


set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/GET_VOLTAGE]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/start_processing_i_1_n_0]

connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_FCLK_CLK0]]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[31]}]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tready]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tlast_out_reg_n_0]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tvalid_out]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tready_out]


set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tready]
set_property MARK_DEBUG false [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/<const0>]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tdata[31]}]

set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[16]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[20]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[24]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[28]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[9]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[11]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[15]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[19]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[23]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[27]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[31]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[10]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[14]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[18]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[22]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[26]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[30]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[13]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[17]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[21]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[25]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[29]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[29]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[25]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[21]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[18]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[14]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[10]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[31]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[28]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[24]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[20]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[17]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[13]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[30]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[27]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[23]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[16]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[9]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[26]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[22]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[19]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[15]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[11]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tdata_out_reg_n_0_[2]}]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tready]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TDATA[25]}]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/M_AXIS_TLAST]


set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_S00_AXIS_inst/input_command[0]_i_1_n_0}]
set_property MARK_DEBUG false [get_nets {design_1_i/AC7606_0/inst/AC7606_v1_0_S00_AXIS_inst/input_command_reg_n_0_[0]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[0]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[1]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[2]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[3]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[4]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[5]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[6]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[7]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[8]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[9]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[10]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[11]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[12]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[13]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[14]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[15]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[16]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[17]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[18]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[19]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[20]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[21]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[22]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[23]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[24]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[25]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[26]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[27]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[28]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[29]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[30]} {design_1_i/axi_dma_0_M_AXIS_MM2S_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/AC7606_0_M00_AXIS_TDATA[0]} {design_1_i/AC7606_0_M00_AXIS_TDATA[1]} {design_1_i/AC7606_0_M00_AXIS_TDATA[2]} {design_1_i/AC7606_0_M00_AXIS_TDATA[3]} {design_1_i/AC7606_0_M00_AXIS_TDATA[4]} {design_1_i/AC7606_0_M00_AXIS_TDATA[5]} {design_1_i/AC7606_0_M00_AXIS_TDATA[6]} {design_1_i/AC7606_0_M00_AXIS_TDATA[7]} {design_1_i/AC7606_0_M00_AXIS_TDATA[8]} {design_1_i/AC7606_0_M00_AXIS_TDATA[9]} {design_1_i/AC7606_0_M00_AXIS_TDATA[10]} {design_1_i/AC7606_0_M00_AXIS_TDATA[11]} {design_1_i/AC7606_0_M00_AXIS_TDATA[12]} {design_1_i/AC7606_0_M00_AXIS_TDATA[13]} {design_1_i/AC7606_0_M00_AXIS_TDATA[14]} {design_1_i/AC7606_0_M00_AXIS_TDATA[15]} {design_1_i/AC7606_0_M00_AXIS_TDATA[16]} {design_1_i/AC7606_0_M00_AXIS_TDATA[17]} {design_1_i/AC7606_0_M00_AXIS_TDATA[18]} {design_1_i/AC7606_0_M00_AXIS_TDATA[19]} {design_1_i/AC7606_0_M00_AXIS_TDATA[20]} {design_1_i/AC7606_0_M00_AXIS_TDATA[21]} {design_1_i/AC7606_0_M00_AXIS_TDATA[22]} {design_1_i/AC7606_0_M00_AXIS_TDATA[23]} {design_1_i/AC7606_0_M00_AXIS_TDATA[24]} {design_1_i/AC7606_0_M00_AXIS_TDATA[25]} {design_1_i/AC7606_0_M00_AXIS_TDATA[26]} {design_1_i/AC7606_0_M00_AXIS_TDATA[27]} {design_1_i/AC7606_0_M00_AXIS_TDATA[28]} {design_1_i/AC7606_0_M00_AXIS_TDATA[29]} {design_1_i/AC7606_0_M00_AXIS_TDATA[30]} {design_1_i/AC7606_0_M00_AXIS_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_dma_0/s_axi_lite_wdata[0]} {design_1_i/axi_dma_0/s_axi_lite_wdata[1]} {design_1_i/axi_dma_0/s_axi_lite_wdata[2]} {design_1_i/axi_dma_0/s_axi_lite_wdata[3]} {design_1_i/axi_dma_0/s_axi_lite_wdata[4]} {design_1_i/axi_dma_0/s_axi_lite_wdata[5]} {design_1_i/axi_dma_0/s_axi_lite_wdata[6]} {design_1_i/axi_dma_0/s_axi_lite_wdata[7]} {design_1_i/axi_dma_0/s_axi_lite_wdata[8]} {design_1_i/axi_dma_0/s_axi_lite_wdata[9]} {design_1_i/axi_dma_0/s_axi_lite_wdata[10]} {design_1_i/axi_dma_0/s_axi_lite_wdata[11]} {design_1_i/axi_dma_0/s_axi_lite_wdata[12]} {design_1_i/axi_dma_0/s_axi_lite_wdata[13]} {design_1_i/axi_dma_0/s_axi_lite_wdata[14]} {design_1_i/axi_dma_0/s_axi_lite_wdata[15]} {design_1_i/axi_dma_0/s_axi_lite_wdata[16]} {design_1_i/axi_dma_0/s_axi_lite_wdata[17]} {design_1_i/axi_dma_0/s_axi_lite_wdata[18]} {design_1_i/axi_dma_0/s_axi_lite_wdata[19]} {design_1_i/axi_dma_0/s_axi_lite_wdata[20]} {design_1_i/axi_dma_0/s_axi_lite_wdata[21]} {design_1_i/axi_dma_0/s_axi_lite_wdata[22]} {design_1_i/axi_dma_0/s_axi_lite_wdata[23]} {design_1_i/axi_dma_0/s_axi_lite_wdata[24]} {design_1_i/axi_dma_0/s_axi_lite_wdata[25]} {design_1_i/axi_dma_0/s_axi_lite_wdata[26]} {design_1_i/axi_dma_0/s_axi_lite_wdata[27]} {design_1_i/axi_dma_0/s_axi_lite_wdata[28]} {design_1_i/axi_dma_0/s_axi_lite_wdata[29]} {design_1_i/axi_dma_0/s_axi_lite_wdata[30]} {design_1_i/axi_dma_0/s_axi_lite_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_dma_0/s_axi_lite_rdata[0]} {design_1_i/axi_dma_0/s_axi_lite_rdata[1]} {design_1_i/axi_dma_0/s_axi_lite_rdata[2]} {design_1_i/axi_dma_0/s_axi_lite_rdata[3]} {design_1_i/axi_dma_0/s_axi_lite_rdata[4]} {design_1_i/axi_dma_0/s_axi_lite_rdata[5]} {design_1_i/axi_dma_0/s_axi_lite_rdata[6]} {design_1_i/axi_dma_0/s_axi_lite_rdata[7]} {design_1_i/axi_dma_0/s_axi_lite_rdata[8]} {design_1_i/axi_dma_0/s_axi_lite_rdata[9]} {design_1_i/axi_dma_0/s_axi_lite_rdata[10]} {design_1_i/axi_dma_0/s_axi_lite_rdata[11]} {design_1_i/axi_dma_0/s_axi_lite_rdata[12]} {design_1_i/axi_dma_0/s_axi_lite_rdata[13]} {design_1_i/axi_dma_0/s_axi_lite_rdata[14]} {design_1_i/axi_dma_0/s_axi_lite_rdata[15]} {design_1_i/axi_dma_0/s_axi_lite_rdata[16]} {design_1_i/axi_dma_0/s_axi_lite_rdata[17]} {design_1_i/axi_dma_0/s_axi_lite_rdata[18]} {design_1_i/axi_dma_0/s_axi_lite_rdata[19]} {design_1_i/axi_dma_0/s_axi_lite_rdata[20]} {design_1_i/axi_dma_0/s_axi_lite_rdata[21]} {design_1_i/axi_dma_0/s_axi_lite_rdata[22]} {design_1_i/axi_dma_0/s_axi_lite_rdata[23]} {design_1_i/axi_dma_0/s_axi_lite_rdata[24]} {design_1_i/axi_dma_0/s_axi_lite_rdata[25]} {design_1_i/axi_dma_0/s_axi_lite_rdata[26]} {design_1_i/axi_dma_0/s_axi_lite_rdata[27]} {design_1_i/axi_dma_0/s_axi_lite_rdata[28]} {design_1_i/axi_dma_0/s_axi_lite_rdata[29]} {design_1_i/axi_dma_0/s_axi_lite_rdata[30]} {design_1_i/axi_dma_0/s_axi_lite_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/AC7606_0_M00_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/AC7606_0_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/AC7606_0_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_dma_0_M_AXIS_MM2S_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axi_dma_0_M_AXIS_MM2S_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axi_dma_0_M_AXIS_MM2S_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/AC7606_0/inst/GET_VOLTAGE]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_S00_AXIS_inst/input_command[0]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_S00_AXIS_inst/input_command_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/axi_dma_0/s_axi_lite_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/axi_dma_0/s_axi_lite_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/start_processing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/start_processing_i_1_n_0]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/clk_block/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/DB[0]} {design_1_i/DB[1]} {design_1_i/DB[2]} {design_1_i/DB[3]} {design_1_i/DB[4]} {design_1_i/DB[5]} {design_1_i/DB[6]} {design_1_i/DB[7]} {design_1_i/DB[8]} {design_1_i/DB[9]} {design_1_i/DB[10]} {design_1_i/DB[11]} {design_1_i/DB[12]} {design_1_i/DB[13]} {design_1_i/DB[14]} {design_1_i/DB[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[0]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[1]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[2]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[3]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[4]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[5]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[6]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[7]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[8]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[9]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[10]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[11]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[12]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[13]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[14]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[15]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[16]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[17]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[18]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[19]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[20]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[21]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[22]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[23]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[24]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[25]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[26]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[27]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[28]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[29]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[30]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tdata[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[0]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[1]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[2]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[3]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[4]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[5]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[6]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[7]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[8]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[9]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[10]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[11]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[12]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[13]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[14]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[15]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[16]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[17]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[18]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[19]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[20]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[21]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[22]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[23]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[24]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[25]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[26]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[27]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[28]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[29]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[30]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tdata[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 2 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tdata[29]} {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tdata[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list design_1_i/BUSY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list design_1_i/CNVST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list design_1_i/CS]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list design_1_i/FRSTDATA]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_result_tvalid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tready]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/m_axis_volt_tvalid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tready]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_const_tvalid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tlast_out_reg_n_0]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tready_out]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_result_tvalid_out]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[1]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[2]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[4]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe21]
set_property port_width 1 [get_debug_ports u_ila_1/probe21]
connect_debug_port u_ila_1/probe21 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[5]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe22]
set_property port_width 1 [get_debug_ports u_ila_1/probe22]
connect_debug_port u_ila_1/probe22 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[6]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe23]
set_property port_width 1 [get_debug_ports u_ila_1/probe23]
connect_debug_port u_ila_1/probe23 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe24]
set_property port_width 1 [get_debug_ports u_ila_1/probe24]
connect_debug_port u_ila_1/probe24 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[8]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe25]
set_property port_width 1 [get_debug_ports u_ila_1/probe25]
connect_debug_port u_ila_1/probe25 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[9]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe26]
set_property port_width 1 [get_debug_ports u_ila_1/probe26]
connect_debug_port u_ila_1/probe26 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[10]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe27]
set_property port_width 1 [get_debug_ports u_ila_1/probe27]
connect_debug_port u_ila_1/probe27 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe28]
set_property port_width 1 [get_debug_ports u_ila_1/probe28]
connect_debug_port u_ila_1/probe28 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[12]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe29]
set_property port_width 1 [get_debug_ports u_ila_1/probe29]
connect_debug_port u_ila_1/probe29 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[13]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe30]
set_property port_width 1 [get_debug_ports u_ila_1/probe30]
connect_debug_port u_ila_1/probe30 [get_nets [list {design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tdata_reg_n_0_[14]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe31]
set_property port_width 1 [get_debug_ports u_ila_1/probe31]
connect_debug_port u_ila_1/probe31 [get_nets [list design_1_i/AC7606_0/inst/AC7606_v1_0_M00_AXIS_inst/s_axis_volt_tready]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe32]
set_property port_width 1 [get_debug_ports u_ila_1/probe32]
connect_debug_port u_ila_1/probe32 [get_nets [list design_1_i/SCLK]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out2]
