# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/design_1_AC7606_0_3.xci
# IP: The module: 'design_1_AC7606_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo || ORIG_REF_NAME==axis_fifo} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/float_divide/float_divide.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_divide || ORIG_REF_NAME==float_divide} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/fix_to_float/fix_to_float.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_to_float || ORIG_REF_NAME==fix_to_float} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/float_float/float_float.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_float || ORIG_REF_NAME==float_float} -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo_ooc.xdc

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo/axis_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo || ORIG_REF_NAME==axis_fifo} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz_ooc.xdc

# IP: D:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/design_1_AC7606_0_3.xci
# IP: The module: 'design_1_AC7606_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_fifo || ORIG_REF_NAME==axis_fifo} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/float_divide/float_divide.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_divide || ORIG_REF_NAME==float_divide} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/fix_to_float/fix_to_float.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_to_float || ORIG_REF_NAME==fix_to_float} -quiet] -quiet

# IP: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/float_float/float_float.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_float || ORIG_REF_NAME==float_float} -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo_ooc.xdc

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_fifo_1/axis_fifo/axis_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_fifo || ORIG_REF_NAME==axis_fifo} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/axis_data_fifo_1/axis_data_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axis_data_fifo || ORIG_REF_NAME==axis_data_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Zynq_other/Zynq_Projects/Zynq_DMA_EMAC_AD7606/Zynq_DMA_EMAC.srcs/sources_1/bd/design_1/ip/design_1_AC7606_0_3/src/clk_wiz_1/clk_wiz_ooc.xdc
